theme: jekyll-theme-hacker
title: MT.lab
logo: "/assets/images/logo.png"
description: Независимое творческое объединение

collections:
  projects:
    output: true
    permalink: /:collection/:title
  news:
    output: true

defaults:
  # Layout default settings
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "newsa"
  - scope:
      path: ""
    values:
      layout: "default"

  # Some additional settings
  - scope:
      path: "assets/images"
    values:
      image: true
