theme: jekyll-theme-hacker
title: MT.lab
logo: "/assets/images/logo.png"
description: Независимое творческое объединение
show_downloads: false
logo: "assets/images/logo.png"

defaults:
  # Layout default settings
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "newsa"

  # Some additional settings
  - scope:
      path: "assets/images"
    values:
      image: true
