theme: jekyll-theme-hacker
title: MT.lab
logo: /assets/images/logo.png
favicon: /assets/images/favicon.png
description: Независимое творческое объединение

page_excerpts: true

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: 'posts'
  per_page: 4
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  posts:
    output: true
  news:
    output: true

defaults:
  # Layout default settings
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
  - scope:
      path: "projects"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

  # Some additional settings
  - scope:
      path: "assets/images"
    values:
      image: true
