name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies and build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          githun_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
