name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies and build
        run: |
          bundle install
          bundle update
          bundle exec jekyll build

      - name: Delete old version
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: |
            rm -rfv !(".htaccess")
          host: ${{secrets.HOSTING_HOST}}
          username: ${{secrets.HOSTING_USER}}
          password: ${{secrets.HOSTING_PASS}}


      - name: Publish site
        uses: garygrossgarten/github-action-scp@v0.6.0
        with:
          local: _site
          remote: ./
          host: ${{secrets.HOSTING_HOST}}
          username: ${{secrets.HOSTING_USER}}
          password: ${{secrets.HOSTING_PASS}}

