name: Deploy to Hosting

on:
  push:
    branches:
      - master

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies and build
        run: |
          bundle install
          bundle update
          bundle exec jekyll build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.HOSTING_SSH_KEY}}" > ~/.ssh/hosting.key
          chmod 600 ~/.ssh/hosting.key
          cat >> ~/.ssh/config << END
          Host hosting
            HostName "${{secrets.HOSTING_HOST}}"
            User "${{secrets.HOSTING_USER}}"
            IdentityFile ~/.ssh/hosting.key
            StrictHostKeyChecking no
          END

      - name: Delete old version
        run: |
          ssh hosting << END
            shopt -s extglob
            rm -rfv !(\.*)
            shopt -u extglob
          END

      - name: Publish site
        run: |
          scp -r _site hosting:./

